name: Deploy Apache and Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Apache HTTP Server
      - name: Install Apache
        run: |
          chmod +x scripts/install_apache.sh
          ./scripts/install_apache.sh

      # Step 3: Install Apache Tomcat
      - name: Install Tomcat
        run: |
          chmod +x scripts/install_tomcat.sh
          ./scripts/install_tomcat.sh
